"""empty message

Revision ID: ebc9916250c3
Revises: 
Create Date: 2020-02-18 17:23:01.281638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc9916250c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artist_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('artist_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('artist_spotify_id')
    )
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table('producers',
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('producer_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('producer_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('albums',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('album_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('album_url', sa.String(length=255), nullable=True),
    sa.Column('art_url', sa.String(length=255), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.String(length=25), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.label_id'], ),
    sa.PrimaryKeyConstraint('album_id'),
    sa.UniqueConstraint('album_spotify_id')
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('track_spotify_id', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('track_name', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('track_url', sa.String(length=255), nullable=True),
    sa.Column('lyrics_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.producer_id'], ),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('track_spotify_id')
    )
    op.create_table('user_album_ratings',
    sa.Column('user_album_rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('best_track_id', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('production_rating', sa.Integer(), nullable=True),
    sa.Column('unique_rating', sa.Integer(), nullable=True),
    sa.Column('enjoyment_rating', sa.Integer(), nullable=True),
    sa.Column('thoughts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['best_track_id'], ['tracks.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_album_rating_id')
    )
    op.create_table('user_track_ratings',
    sa.Column('user_track_rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('listens', sa.Integer(), nullable=True),
    sa.Column('last_listen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_track_rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_track_ratings')
    op.drop_table('user_album_ratings')
    op.drop_table('tracks')
    op.drop_table('albums')
    op.drop_table('users')
    op.drop_table('producers')
    op.drop_table('labels')
    op.drop_table('artists')
    # ### end Alembic commands ###
